import { defineField } from "sanity";

export const allFeaturesField = defineField({
  name: 'allFeatures',
  title: 'All Features',
  type: 'object',
  fieldsets: [
    {
      name: 'mainFeatures',
      title: 'Main Features',
      options: {collapsible: true, collapsed: false},
    },
    {
      name: 'keyFeatures',
      title: 'Key Features',
      options: {collapsible: true, collapsed: true},
    },
  ],
  fields: [
    // MAIN FEATURES
    {
      name: 'sqft',
      title: 'Total SQFT (AG + BG + GS)',
      type: 'string',
      fieldset: 'mainFeatures',
    },
    {
      name: 'mainHouseSqft',
      title: 'Main House SQFT',
      type: 'string',
      fieldset: 'mainFeatures',
    },
    {
      name: 'basementSqft',
      title: 'Basement SQFT',
      type: 'string',
      fieldset: 'mainFeatures',
    },
    {
      name: 'garageSuiteSqft',
      title: 'Garage Suite SQFT',
      type: 'string',
      fieldset: 'mainFeatures',
    },
    {
      name: 'bedrooms',
      title: 'Total Beds',
      type: 'string',
      fieldset: 'mainFeatures',
    },
    {
      name: 'bathrooms',
      title: 'Total Bath',
      type: 'string',
      fieldset: 'mainFeatures',
    },

    // KEY FEATURES
    {name: 'kitchen', title: 'Kitchen', type: 'number', fieldset: 'keyFeatures'},
    {name: 'spiceKitchen', title: 'Spice Kitchen', type: 'boolean', fieldset: 'keyFeatures'},
    {
      name: 'spiceKitchenTotal',
      title: 'Spice Kitchen in Total',
      type: 'string',
      fieldset: 'keyFeatures',
    },
    {name: 'fullBath', title: 'Full Bath', type: 'number', fieldset: 'keyFeatures'},
    {name: 'livingRoom', title: 'Living Room', type: 'number', fieldset: 'keyFeatures'},
    {name: 'bonusRoom', title: 'Bonus Room as 1', type: 'boolean', fieldset: 'keyFeatures'},
    {
      name: 'bonusRoomTotal',
      title: 'Bonus Room as Total',
      type: 'string',
      fieldset: 'keyFeatures',
    },
    {name: 'openToAbove', title: 'Open to Above', type: 'boolean', fieldset: 'keyFeatures'},
    {
      name: 'openToAboveTotal',
      title: 'Open to Above Total',
      type: 'string',
      fieldset: 'keyFeatures',
    },
    {
      name: 'ceilingHeight',
      title: 'Ceiling Height (in ft)',
      type: 'string',
      fieldset: 'keyFeatures',
    },
    {
      name: 'doubleBasement',
      title: 'Double Basement',
      type: 'boolean',
      fieldset: 'keyFeatures',
    },
    {
      name: 'treatedWoodDeck',
      title: 'Treated Wood Deck',
      type: 'boolean',
      fieldset: 'keyFeatures',
    },
    {name: 'concretePad', title: 'Concrete Pad', type: 'boolean', fieldset: 'keyFeatures'},
    {name: 'compositeDeck', title: 'Composite Deck', type: 'boolean', fieldset: 'keyFeatures'},
    {name: 'vinylDeck', title: 'Vinyl Deck', type: 'boolean', fieldset: 'keyFeatures'},
    {name: 'rearBalcony', title: 'Rear Balcony as 1', type: 'boolean', fieldset: 'keyFeatures'},
    {
      name: 'rearBalconyTotal',
      title: 'Rear Balcony as Total',
      type: 'number',
      fieldset: 'keyFeatures',
    },
    {name: 'frontBalcony', title: 'Front Balcony', type: 'boolean', fieldset: 'keyFeatures'},
    {name: 'featureWalls', title: 'Feature Walls', type: 'boolean', fieldset: 'keyFeatures'},
    {name: 'vinylFlooring', title: 'Vinyl Flooring', type: 'boolean', fieldset: 'keyFeatures'},
    {name: 'tiledFlooring', title: 'Tiled Flooring', type: 'boolean', fieldset: 'keyFeatures'},
    {
      name: 'tripleCarGarage',
      title: 'Triple Car Garage',
      type: 'boolean',
      fieldset: 'keyFeatures',
    },
    {
      name: 'doubleCarGarage',
      title: 'Double Car Garage',
      type: 'boolean',
      fieldset: 'keyFeatures',
    },
    {
      name: 'separateSideEntrance',
      title: 'Separate Side Entrance',
      type: 'boolean',
      fieldset: 'keyFeatures',
    },
    {
      name: 'mainFloorFullBedBath',
      title: 'Main Floor Full Bed & Bath',
      type: 'boolean',
      fieldset: 'keyFeatures',
    },
    {
      name: 'rentalGarageSuite',
      title: 'Rental Garage Suite',
      type: 'boolean',
      fieldset: 'keyFeatures',
    },
    {name: 'parkFacing', title: 'Park Facing', type: 'boolean', fieldset: 'keyFeatures'},
    {
      name: 'legalFinishedBasement',
      title: 'Legal Finished Basement',
      type: 'boolean',
      fieldset: 'keyFeatures',
    },
    {
      name: 'ownerSuiteBasement',
      title: 'Owner Suite Basement',
      type: 'boolean',
      fieldset: 'keyFeatures',
    },
    {
      name: 'sevenBedsFiveBath',
      title: '7 Beds & 5 Bath',
      type: 'string',
      fieldset: 'keyFeatures',
    },
    {name: 'airportNearby', title: 'Airport Nearby', type: 'boolean', fieldset: 'keyFeatures'},
    {
      name: 'playgroundSchoolsNearby',
      title: 'Playground & Schools Nearby',
      type: 'boolean',
      fieldset: 'keyFeatures',
    },
    {name: 'golfNearby', title: 'Golf Near By', type: 'boolean', fieldset: 'keyFeatures'},
    {name: 'schoolNearby', title: 'School Near By', type: 'boolean', fieldset: 'keyFeatures'},
    {name: 'walkout', title: 'Walkout', type: 'boolean', fieldset: 'keyFeatures'},
    {
      name: 'partialWalkout',
      title: 'Partial Walkout',
      type: 'boolean',
      fieldset: 'keyFeatures',
    },
    {name: 'regularLot', title: 'Regular Lot', type: 'boolean', fieldset: 'keyFeatures'},
    {
      name: 'vaultedCeiling',
      title: 'Vaulted Ceiling',
      type: 'boolean',
      fieldset: 'keyFeatures',
    },
    {
      name: 'indentCeiling',
      title: 'Indent Ceiling/s',
      type: 'boolean',
      fieldset: 'keyFeatures',
    },
    {
      name: 'ceilingHighCabinets',
      title: 'Ceiling High Cabinets',
      type: 'boolean',
      fieldset: 'keyFeatures',
    },
    {name: 'dropCeilings', title: 'Drop Ceiling/s', type: 'boolean', fieldset: 'keyFeatures'},
    {name: 'carpetFloor', title: 'Carpet Floor', type: 'boolean', fieldset: 'keyFeatures'},
    {name: 'tenFTceilings', title: '10 ft Ceilings', type: 'boolean', fieldset: 'keyFeatures'},
    {
      name: 'twentyFTceilings',
      title: '20 ft Ceilings',
      type: 'boolean',
      fieldset: 'keyFeatures',
    },
  ],
})