import {defineField} from 'sanity'

export const garageField = defineField({
  name: 'garage',
  title: 'Garage',
  type: 'string',
  options: {
    list: [
      {title: '2 Outdoor Stalls', value: '2 Outdoor Stalls'},
      {title: '220 Volt Wiring', value: '220 Volt Wiring'},
      {title: 'Double Carport', value: 'Double Carport'},
      {title: 'Double Garage Attached', value: 'Double Garage Attached'},
      {title: 'Double Garage Detached', value: 'Double Garage Detached'},
      {title: 'Double Front Attach Garage', value: 'Double Front Attach Garage'},
      {title: 'Double Rear Detach Garage', value: 'Double Rear Detach Garage'},
      {title: 'Double Indoor', value: 'Double Indoor'},
      {title: 'Front Drive Access', value: 'Front Drive Access'},
      {title: 'Front/Rear Drive Access', value: 'Front/Rear Drive Access'},
      {title: 'Heated', value: 'Heated'},
      {title: 'Insulated', value: 'Insulated'},
      {title: 'No Garage', value: 'No Garage'},
      {title: 'Over Sized', value: 'Over Sized'},
      {title: 'Parkade', value: 'Parkade'},
      {title: 'Parking Pad Cement/Paved', value: 'Parking Pad Cement/Paved'},
      {title: 'Quad or More Attached', value: 'Quad or More Attached'},
      {title: 'Quad or More Detached', value: 'Quad or More Detached'},
      {title: 'Rear Drive Access', value: 'Rear Drive Access'},
      {title: 'RV Parking', value: 'RV Parking'},
      {title: 'Shop', value: 'Shop'},
      {title: 'Single Carport', value: 'Single Carport'},
      {title: 'Single Garage Attached', value: 'Single Garage Attached'},
      {title: 'Single Garage Detached', value: 'Single Garage Detached'},
      {title: 'Single Indoor', value: 'Single Indoor'},
      {title: 'Stall', value: 'Stall'},
      {title: 'Tandem', value: 'Tandem'},
      {title: 'Triple Garage Attached', value: 'Triple Garage Attached'},
      {title: 'Triple Garage Detached', value: 'Triple Garage Detached'},
      {title: 'Underground', value: 'Underground'},
      {title: 'See Remarks', value: 'See Remarks'},
      {title: 'EV Charging Station', value: 'EV Charging Station'},
      {title: 'No Parking', value: 'No Parking'},
      {title: 'Front Single Garage Home', value: 'Front Single Garage Home'},
      {title: 'Rear Single Garage Home', value: 'Rear Single Garage Home'},
      {title: 'Front Tripe Garage Home', value: 'Front Tripe Garage Home'},
      {title: 'Rear Triple Garage Home', value: 'Rear Triple Garage Home'},
      {title: 'Front Quadruple Garage Home', value: 'Front Quadruple Garage Home'},
      {title: 'Rear Quadruple Garage Home', value: 'Rear Quadruple Garage Home'},
    ],
    layout: 'dropdown',
  },
  description: 'Select the garage type.',
})
